name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        build: [linux, windows, macos]
        
        include:
          - build: linux
            name: "Linux"
            os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
            
          - build: windows
            name: "Windows"
            os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc
            
          - build: macos
            name: "macOS"
            os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin
  
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install OpenCL ICD
        shell: bash
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev
        if: ${{ matrix.name == 'Linux' }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          
      - name: Cache Cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ matrix.name }}-cargo-${{ hashFiles('Cargo.toml') }}
            
      - name: Cache Cargo target
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.name }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
